version: '3.4'

services:
  local.functions:
    container_name: local.functions
    build:
      context: ./src/FunctionApp
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AzureWebJobsStorage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://azurite:local.storage.emulator/devstoreaccount1;QueueEndpoint=http://local.storage.emulator:10001/devstoreaccount1;TableEndpoint=http://local.storage.emulator:10002/devstoreaccount1;
      - AzureWebJobsSecretStorageType=files
      - DiscordOptions__Token=${DISCORD_TOKEN}
      - DiscordOptions__GuildId=${DISCORD_GUILDID}
      - DiscordOptions__ChannelId=${DISCORD_CHANNELID}
      - BlobStorageImageSourceOptions__ConnectionString=DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://local.storage.emulator:10000/devstoreaccount1;QueueEndpoint=http://local.storage.emulator:10001/devstoreaccount1;
      - BlobStorageImageSourceOptions__ContainerName=images
      - BlobStorageImageSourceOptions__FolderPath=testfolder
    depends_on:
      - local.storage.emulator
    volumes:
      - ./src/FunctionApp/dev_secrets:/azure-functions-host/Secrets

  local.storage.emulator:
    image: mcr.microsoft.com/azure-storage/azurite:3.30.0
    container_name: local.storage.emulator
    command: azurite --loose --disableProductStyleUrl --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log
    ports:
        - 10000:10000
        - 10001:10001
        - 10002:10002
