version: '3.4'

services:
  local.functions.isolated:
    container_name: local.functions.isolated
    build:
      context: ./src
      dockerfile: FunctionApp.Isolated/Dockerfile
    ports:
      - 8080:80
    environment:
      - WEBSITE_HOSTNAME=localhost:8080
      - AzureWebJobsStorage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=https;BlobEndpoint=http://local.storage.emulator:10000/devstoreaccount1;QueueEndpoint=http://local.storage.emulator:10001/devstoreaccount1;TableEndpoint=http://local.storage.emulator:10002/devstoreaccount1;
      - AzureWebJobsSecretStorageType=files
      - DiscordConfiguration__Token=${DISCORD_TOKEN}
      - DiscordConfiguration__GuildId=${DISCORD_GUILDID}
      - DiscordConfiguration__ChannelId=${DISCORD_CHANNELID}
      - BlobStorageImageSourceOptions__ConnectionString=DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://local.storage.emulator:10000/devstoreaccount1;QueueEndpoint=http://local.storage.emulator:10001/devstoreaccount1;
      - BlobStorageImageSourceOptions__ContainerName=images
      - BlobStorageImageSourceOptions__FolderPath=testfolder
      - ImageIndexOptions__ConnectionString=DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://local.storage.emulator:10000/devstoreaccount1;QueueEndpoint=http://local.storage.emulator:10001/devstoreaccount1;
      - ImageIndexOptions__ContainerName=index
      - ImageAnalysisConfiguration__Endpoint=${COGNITIVESERVICES_ENDPOINT}
      - FeatureSettings__DisableTimedSending=true
      - FeatureSettings__DisableDiscordSending=true
    depends_on:
      - local.storage.emulator
    volumes:
      - ./src/FunctionApp.Isolated/dev_secrets:/azure-functions-host/Secrets

  local.storage.emulator:
    image: mcr.microsoft.com/azure-storage/azurite:3.30.0
    container_name: local.storage.emulator
    command: azurite --loose --disableProductStyleUrl --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002 --location /workspace --debug /workspace/debug.log
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
